'use client';
import { ArrowDown, ArrowRight, FlaskConical, LockKeyhole, Play, Sparkles, TrendingUp } from 'lucide-react';
const metrics=[{value:'₹1,176.5Cr',label:'FY25 revenue from operations',note:'Publicly reported FY25 figure'},{value:'₹331.2Cr',label:'FY25 marketing expenditure',note:'Reported marketing spend — not CAC'},{value:'₹140Cr+',label:'Store FY25 revenue',note:'Reported AstroTalk Store revenue'}];
const channels=[
{n:'01',name:'EX FILES',tag:'RELATIONSHIP REALITY',headline:'He’s getting married in 23 days. He called me last night.',desc:'Anonymous relationship dilemmas become episodic entertainment: story, audience verdict, astrologer perspective, cliffhanger and a private path to help.',status:'LIVE PROTOTYPE',icon:'♥',live:true},
{n:'02',name:'KUNDLI COURT',tag:'PARTICIPATORY REALITY',headline:'Two stories. Two charts. One verdict.',desc:'Couples bring the disagreement. Both sides get heard. The audience votes before an astrologer reveals the relationship pattern.',status:'QUEUED',icon:'⚖',live:false},
{n:'03',name:'WTF, ASTRO?',tag:'GEN-Z / SCEPTICS',headline:'Astrology for people who think astrology is bullshit.',desc:'A sceptical creator tests predictions, compatibility and astrologer claims in public. Entertainment first; belief is never required.',status:'QUEUED',icon:'?',live:false},
{n:'04',name:'MONEY KARMA',tag:'CAREER / FOUNDERS',headline:'Success. Failure. Decisions. Destiny.',desc:'Founders, professionals and creators revisit pivotal decisions through the lens of timing, patterns and astrology.',status:'QUEUED',icon:'₹',live:false},
{n:'05',name:'AFTER DARK',tag:'PRIVATE INTENT',headline:'Questions people search at 2AM and never ask publicly.',desc:'An anonymous, carefully moderated format around breakups, infidelity, loneliness, family conflict and the questions people hide.',status:'QUEUED',icon:'☾',live:false}];
function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});}
export default function Home(){return <main>
<nav className="nav"><button className="brand" onClick={()=>go('top')}><span>N/</span> ASTROTALK</button><div className="navRight"><i>INDEPENDENT VENTURE EXPERIMENT</i><b>VAIBHAV VENU</b></div></nav>
<section id="top" className="hero section"><div className="heroGrid"/><div className="eyebrow"><i/> EXPERIMENT 01 · CONTENT LABS</div><h1>AstroTalk knows how<br/>to <em>buy</em> attention.</h1><h2>What if it started <span>owning it?</span></h2><p className="heroCopy">A 90-day venture experiment to test whether content can become an owned media business — generating audience, transactions and IP instead of disappearing when the ad budget stops.</p><div className="actions"><button className="primary" onClick={()=>go('proof')}>ENTER THE LAB <ArrowRight size={17}/></button><button className="ghost" onClick={()=>go('thesis')}>VIEW THE THESIS <ArrowDown size={15}/></button></div><div className="rules"><div><b>₹10L</b><span>MAX TEST CAPITAL</span></div><div><b>90</b><span>DAYS</span></div><div><b>3</b><span>OWNERS / CHANNEL</span></div><div><b>5</b><span>CHANNEL HYPOTHESES</span></div><div><b className="orange">01</b><span>RULE: EARN THE NEXT ₹</span></div></div><small>Built from public information. No AstroTalk internal data used. Forward-looking economics are model assumptions, not company forecasts.</small></section>
<section id="proof" className="proof section"><div className="sectionNo">01 / WHY NOW</div><div className="split"><h3>The machine already<br/>knows how to scale.</h3><p>This is not a case for “doing more social media.” It asks whether an organisation already spending heavily to acquire demand can build media assets that compound.</p></div><div className="metrics">{metrics.map((m,i)=><article key={m.value}><div className="metricTop"><span>0{i+1}</span><TrendingUp size={16}/></div><strong>{m.value}</strong><h4>{m.label}</h4><p>{m.note}</p></article>)}</div><div className="store"><div className="storeKicker"><Sparkles size={15}/> THE PRECEDENT</div><h4>A small adjacent bet can earn the right to become a business.</h4><div className="storeFlow"><div><b>₹30L</b><span>reported initial Store pilot</span></div><ArrowRight/><div><b>₹40Cr</b><span>reported subsequent investment</span></div><ArrowRight/><div><b>1.6M+</b><span>reported 2025 orders</span></div><ArrowRight/><div><b>300+</b><span>reported SKUs</span></div><ArrowRight/><div><b>24%</b><span>reported repeat purchase</span></div></div><small>Public figures are context, not evidence that Content Labs will work.</small></div></section>
<section id="thesis" className="thesis section"><div className="sectionNo">02 / THE BET</div><h3>Don’t just optimise the ad.<br/><span>Own what people came to watch.</span></h3><div className="systems"><div><label>THE RENTED LOOP</label><div className="chain"><span>₹</span>→<span>CREATIVE</span>→<span>DISTRIBUTION</span>→<span>CUSTOMER</span>→<span>TRANSACTION</span></div><p>Turn distribution off and the acquisition engine slows with it.</p></div><div className="owned"><label>THE OWNED LOOP</label><div className="chain"><span>STORY</span>→<span>AUDIENCE</span>→<span>COMMUNITY</span>→<span>TRANSACTION</span>↻</div><p>Every good story can create the audience, submission and demand for the next one.</p></div></div><div className="question"><span>THE EXPERIMENT</span><p>Can AstroTalk systematically manufacture media properties that <b>earn attention on their own</b>, create measurable commercial intent, and eventually survive as businesses independent of paid acquisition?</p></div></section>
<section id="lab" className="lab section"><div className="labTop"><div><div className="sectionNo">03 / CONTENT LABS</div><h3>Five bets on<br/><em>attention.</em></h3></div><p>Small autonomous channel pods. Shared infrastructure. Fixed capital gates. Kill aggressively. Scale only when audience and economics earn the next cheque.</p></div><div className="channels">{channels.map(c=><article key={c.n} className={c.live?'live':''}><div className="icon">{c.icon}</div><div className="meta"><span>{c.n} / {c.tag}</span><h4>{c.name}</h4></div><div className="idea"><strong>{c.headline}</strong><p>{c.desc}</p></div><div className="status">{c.live?<Play size={12} fill="currentColor"/>:<LockKeyhole size={12}/>} {c.status}</div><ArrowRight className="arrow" size={20}/></article>)}</div><div className="labRule"><FlaskConical/><div><span>LAB RULE 01</span><strong>Only EX FILES gets capital first.</strong><p>Five hypotheses do not mean five simultaneous builds. Fund one cheap test, learn, then kill it or earn the right to spend more.</p></div><button onClick={()=>alert('EX FILES opens in Cluster 2')}>OPEN EX FILES <ArrowRight size={15}/></button></div></section>
<footer><div><span>NEXT / ASTROTALK</span><b>EXPERIMENT 01 · CONTENT LABS</b></div><p>An independent venture thesis by Vaibhav Venu.</p><button onClick={()=>go('top')}>BACK TO TOP ↑</button></footer></main>}